# Generated by Django 3.2.4 on 2021-06-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(upload_to='image/skills'),
        ),
    ]
