# Generated by Django 3.2.4 on 2021-06-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_alter_skill_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('technology', models.CharField(max_length=240)),
                ('description', models.TextField()),
            ],
        ),
    ]
