# Generated by Django 3.2.4 on 2021-06-21 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 6, 21, 4, 16, 45, 694455, tzinfo=utc), upload_to='image/project'),
            preserve_default=False,
        ),
    ]
