# Generated by Django 3.2.4 on 2021-06-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0004_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=40)),
                ('comments', models.TextField()),
            ],
        ),
    ]
